version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_OLLAMA_URL=http://host.docker.internal:11434/api/chat
      - REACT_APP_BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_MAPS_KEY=${GOOGLE_MAPS_KEY}
    volumes:
      - ./backend:/app
